name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DOCKER_HUB_USERNAME: farhanluckali
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_IMAGE: python-github-action-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}
    
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_IMAGE}}:${{ github.sha }}
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_IMAGE}}:latest
